# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13afa79d226757a69bfd7eb2974150ef48cab798ff6970130fba5db9f8fd75080a91d8c05d05ca54a0e5a636e60c3d81289bcb565032ec034f995e4d425f14bd

test:
  secret_key_base: 1a5a83c92fff687021daee8255ac8cc205267a25d0537883d44bd85213bc71d6cc7e546590b7d40f00977c86ad0bcc94eb101edb624246344cb4682c9d1f66ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
